version: "3.8"
services:
  db:
    image: postgres
    container_name: insight-beam-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: insight-beam-db
      POSTGRES_PASSWORD: insight-beam-password
      POSTGRES_DB: insight-beam
    volumes:
      - insight-beam-db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: insight-beam-pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: yumnaahwaris@gmail.com
      PGADMIN_DEFAULT_PASSWORD: insight-beam-password
    volumes:
      - insight-beam-pgadmin-data:/var/lib/pgadmin

volumes:
  insight-beam-db-data:
  insight-beam-pgadmin-data:
